### ISSUE TITLE
Emojis are too small on iOS

### ISSUE THREAD

**Issue by 0Supa** [chatsen/chatsen#1]
![image](https://i.imgur.com/83sydUV.png)

**Comment by williambulin** [comment]
See: https://github.com/flutter/flutter/issues/28894 as to why it happens
This is an issue with the Flutter SDK but has very hacky workarounds, so might be fixed.

**Comment by williambulin** [comment]
Adding that this also happens on Android.

**Comment by iosephmagno** [comment]
So emojis display weirdly / tiny and you mark it as low priority? That’s like chat and social media apps cannot be built in flutter. That should be p2!
