### ISSUE TITLE
[iOS] Diaeresis in links crashes the app.

### ISSUE THREAD

**Issue by StephanBruh** [chatsen/chatsen#113]
When you open a link with diaeresis in the link, it crashes chatsen.

example:
https://www.google.com/search?q=testö 

Found by Paauulli#4848, Cyclone#2967 could reproduce.

**Comment by PaauullI** [comment]
if the text of the url was generated with the built-in javascript function "encodeUriComponent()", diaeresis work.

example: 
https://www.google.com/search?q=testö doesnt work

https://www.google.com/search?q=testo%CC%88 does work

**Comment by williambulin** [comment]
Fixed in build 56.
