### ISSUE TITLE
Features suggestion

### ISSUE THREAD

**Issue by 21mtd** [chatsen/chatsen#117]
- [✔️] 1. Copy someone's message by holding on it or show a [copy popup](https://i.imgur.com/QcJDYN4.png)

2. Tap on a username in chat should show some options like User Info, whisper, mention, chat search, block and Add friend maybe (User Info shows some info like in Chatterino: username, ID, created date, current sub tier, months)

**Comment by StephanBruh** [comment]
Holding a message already copies it to your clipboard on the latest version

**Comment by 21mtd** [comment]
Oh it is, somehow its really slow to show Paste so i thought its not working FeelsDankMan but would be nice to show a popup or something to confirm its copied 😄

**Comment by StephanBruh** [comment]
> Oh it is, somehow its really slow to show Paste so i thought its not working FeelsDankMan but would be nice to show a popup or something to confirm its copied 😄

Agree
