### ISSUE TITLE
Load Recent Messages button doesn't do anything

### ISSUE THREAD

**Issue by Felanbird** [chatsen/chatsen#123]
Whether or not the setting is toggled on or off, message history loads anyway.

~~Possibly during the fix, might want to take a look at offering a prompt for users to opt in, which would toggle the setting on, similar to DankChat.~~ i remembered there was a prompt xd

Tested on `1.0.52+52` on both Android & IOS, also personally tested on `1.0.50+46` Android

**Comment by williambulin** [comment]
Strangely it seems like I have never used the option variable anywhere, going to fix that urgently.
You can trigger the prompt at the beginning that shows the option when you start the application for the first time by toggling the first option in the settings and restarting the app if needed

**Comment by williambulin** [comment]
Should be fixed in commit 4fdc56d6ad4597d617daf5da1c826850de4dfe49.
