### ISSUE TITLE
Unable to adjust video quality 

### ISSUE THREAD

**Issue by kyleboas** [chatsen/chatsen#138]
For the media player I am unable to adjust the video quality. The only option I have is “Auto”. 

From what I’m aware this is due to something related to this: https://discuss.dev.twitch.tv/t/is-there-a-way-to-limit-qualities-used-in-twitch-player/6678/2

iPhone 6s
iOS 14.3

**Comment by hoserfx** [comment]
Same.

iPhone Xr
iOS 15
