### ISSUE TITLE
Refresh button for the chat

### ISSUE THREAD

**Issue by ttturkii** [chatsen/chatsen#139]
![Untitled56_20211012183917](https://user-images.githubusercontent.com/92387196/136986979-ff92c985-d2fe-47da-b135-4df0d2b62b98.png) 
I tried to draw an illustration of what I mean

**Comment by Void48** [comment]
Reload button would be great no need to restart app when a emote is added +1

**Comment by basedbidoof** [comment]
Reload emotes would be a nice feature. Sure we can open/close the app, but that takes more time
