### ISSUE TITLE
Option for transparency effects

### ISSUE THREAD

**Issue by rankn1ne** [chatsen/chatsen#140]
I really like chatsen, but it's hitting battery life pretty hard. I assume that transparency effects may be a part of this problem. So having an option to turn them off would be POGGERS.

xqcL ❤

**Comment by Void48** [comment]
> I really like chatsen, but it's hitting battery life pretty hard. I assume that transparency effects may be a part of this problem. So having an option to turn them off would be POGGERS.
> 
> xqcL ❤

this option could also be called ''Lite mode'' 🤔
