### ISSUE TITLE
Delayed load of chat history replaces certain messages

### ISSUE THREAD

**Issue by acdvs** [chatsen/chatsen#152]
If you have chat history enabled and you open the app, a channel will initially be empty for a few seconds. If you send a message during this loading time, it will get replaced/overwritten by the history that's loaded in. This is also the case for messages sent by others.

All messages sent/received in the time chat history is loading should be _appended_ to the chat history.

**Comment by williambulin** [comment]
The proper fix for this is to sort messages by timestamp and filter by existing ids, which is done and therefore fixed in Chatsen 2/dart_twitch from now on.
