### ISSUE TITLE
Problem this chat history "bug"

### ISSUE THREAD

**Issue by BfGanimeshnik** [chatsen/chatsen#160]
Hello, it does not show the chat history for me, but it does for a friend. I have an android, he has an iPhone.
![image](https://user-images.githubusercontent.com/55851088/145483154-d027aee3-b88a-45fd-9492-81d7a2f333e2.png)
![image](https://user-images.githubusercontent.com/55851088/145483177-69ff06cc-72f8-48aa-b6bd-865b8605d6ef.png)

**Comment by LosFarmosCTL** [comment]
The chat history is provided by a 3rd party service, if it does not load for you it is most likely an issue with connecting to that server.

Can you verify that you have access to this website in your normal browser?

https://recent-messages.robotty.de/api/v2/recent-messages/forsen
