### ISSUE TITLE
Implement RFC workaround to fix combo-emojis

### ISSUE THREAD

**Issue by Felanbird** [chatsen/chatsen#169]
Created by @Mm2PL

Mm2PL has created an RFC for the following: https://gist.github.com/Mm2PL/982c76964fe53f80fcf6b6963bba049f Rendered LaTeX PDF: https://mm2pl.github.io/emoji_rfc.pdf, which is a workaround for twitchdev/issues#307.

Twitch's chat server removes the ZERO WIDTH JOINER character which makes posting and receiving combined emoji (like 👨‍🌾) impossible. They just get turned into their parts, in this case 👨🌾.

I'd like for Chatsen to replace U+200D (ZERO WIDTH JOINER) with U+E0002 (no official name) when sending/receiving messages as  described in the RFC.

This fix has already been implemented into both Chatterino (Chatterino/chatterino2#3469) and Dankchat (flex3r/DankChat@d5303b9 ) respectively.

Currently combo emojis on Chatsen look like this:

![image](https://user-images.githubusercontent.com/41973452/149885504-a310f2b9-0f74-48aa-9832-c729bd3c92ee.png)

Compared to Chatterino & Dankchat post-fix:
![image](https://user-images.githubusercontent.com/41973452/149884791-ad5a3615-4b5f-4d86-8533-83a0641f4027.png)
![image](https://user-images.githubusercontent.com/41973452/149885459-80176cc7-8f3c-4879-8cef-37dc27494be3.png)

**Comment by williambulin** [comment]
Will look into it

**Comment by williambulin** [comment]
Fixed in 0350eb5fc6dba3509390de3486e5b799b6c249e9.

**Comment by Felanbird** [comment]
> Fixed in [0350eb5](https://github.com/chatsen/chatsen/commit/0350eb5fc6dba3509390de3486e5b799b6c249e9).

I'll take your word for it because I cba to build and test myself. 👍

**Comment by williambulin** [comment]
> > Fixed in [0350eb5](https://github.com/chatsen/chatsen/commit/0350eb5fc6dba3509390de3486e5b799b6c249e9).
> 
> I'll take your word for it because I cba to build and test myself. 👍

Sure no problem! Just for information, you don't have to build it yourself as every commit triggers an automatic build with GitHub Actions so in the future you can just grab the artifact produced if you wanna try something out without building the app yourself.

In the case of the commit 0350eb5fc6dba3509390de3486e5b799b6c249e9 in question, it'd be
https://github.com/chatsen/chatsen/actions/runs/1712087028

**Comment by Felanbird** [comment]
> In the case of the commit [0350eb5](https://github.com/chatsen/chatsen/commit/0350eb5fc6dba3509390de3486e5b799b6c249e9) in question, it'd be https://github.com/chatsen/chatsen/actions/runs/1712087028

Ah, I didn't even think to check the Github actions because I was used to the convenience of Chatterino's nightly builds always being at the same link.

**Comment by Felanbird** [comment]
Functionality works as intended. 👍 

Although I do want to mention I was prompted to "update" from `1.1.70`(?) to `1.1.73+73` so the actions might need a version bump.

**Comment by williambulin** [comment]
> Functionality works as intended. 👍
> 
> Although I do want to mention I was prompted to "update" from `1.1.70`(?) to `1.1.73+73` so the actions might need a version bump.

Yeah currently I don't manually update the version number in the pubspec.yaml file and the workflow only uses the correct version when specified via a tag.
Since I doubt there's people using the actions build, I haven't added a nightly updater for it (it always pulls from actual releases right now) but I will probably do that at some point down the road
