### ISSUE TITLE
mod commands

### ISSUE THREAD

**Issue by Pandahsss** [chatsen/chatsen#180]
I am a moderator of some channels and it would make it easier for me to be able to use commands from Twitch itself such as /poll from the application, since it is not possible on mobile Twitch

**Comment by Felanbird** [comment]
There is no API for `/poll` - it cannot be implemented into any third party applications.

**Comment by Pandahsss** [comment]
I was testing all the Twitch mobile chats and there was one where you put a url to watch the stream, and when you put the popout you could use commands
