### ISSUE TITLE
7TV Emotes Stopped Showing

### ISSUE THREAD

**Issue by net00-1** [chatsen/chatsen#214]
After 7TV deprecated the v2 API, emotes no longer show up. The v3 API apparently must be used.

Can you please check if this can be updated in Chatsen?

**Comment by net00-1** [comment]
I noticed the new release a few hours ago, thanks!

**Comment by williambulin** [comment]
No worries, it'll take some time to arrive on the App Store because Apple is slow to approve but it should already be there for Android users.
