### ISSUE TITLE
Support 7TV subscriber features

### ISSUE THREAD

**Issue by Raziel7893** [chatsen/chatsen#221]
Is it possible to support the 7tv subscriber features?
- colored Namefonts 
  - enabling your own Font (7tv extensions only show Fonts to others, if you are online with an supported client)
    - as of now only the 7tv browser extension, FFZ and chatterino7 supports that
  - showing the fonts of other users 
- picking and showing of personal emotes?

**Comment by williambulin** [comment]
Name paints won't be supported for performance and battery usage reasons.
Personal emotes won't be supported due to the same reasons, opening another websocket would be too taxing
