### ISSUE TITLE
Add set aspect ratio to the new fullscreen player

### ISSUE THREAD

**Issue by StephanBruh** [chatsen/chatsen#87]
If your phone has a bigger aspect ratio then 16:9 the player gets cut off when in fullscreen.

![image](https://user-images.githubusercontent.com/19285400/125157015-d2896480-e168-11eb-8455-268ba07cc7ea.png)
screenshot from a oneplus 6t (19.5:9)

**Comment by williambulin** [comment]
Aspect ratio is only used with a vertical orientation so that's not what's causing the issue here.
The player should be filling the entire space (ignoring even the notch) so something's in the Widget layout is causing this.
Will investigate

**Comment by williambulin** [comment]
Fixed in 25924a5
