### ISSUE TITLE
User banned

### ISSUE THREAD

**Issue by StephanBruh** [chatsen/chatsen#98]
When you get banned in a channel would be great to be alerted by that and maybe bypass the ban, so you can still read chat? Right now when you get banned no messages appear. And when you get unbanned you need to restart the app to see chat again and chat yourself

**Comment by williambulin** [comment]
The ban bypass would be with a future anonymous read-only connection instead of using your credentials which is eventually planned. Same for messages. Would be easy to implement once the state system for the IRC client is ready.
